repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: ['--config=.black.ini']
        language_version: python3
  - repo: https://github.com/PyCQA/flake8
    rev: "4.0.1"
    hooks:
      - id: flake8
  - repo: https://github.com/timothycrosley/isort
    rev: "5.10.1"
    hooks:
      - id: isort
        args: ['--settings-path=.isort.cfg']
  - repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
      - id: bandit
        args: ["--ini=.bandit", "--recursive", "-a=file"]
