name: yml-env
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - pandas
  - pyomo
  - plotly
  - networkx
  - scipy
  - pyyaml
  - tqdm
  - seaborn
  - pydot
#  - pip
#  - pip:
#    - yaml
 