name: yml-env
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - pandas
  - pyomo
  - plotly
  - networkx
  - scipy
#  - yaml # is being ignored here, try pip instead
  - tqdm
  - pip:
    - yaml
 