name: CBC-optimizer CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build tool
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Dockerfile
        run: docker build --pull -t oogeso --target dev -f Dockerfile .
      - name: Test cbc
        run: docker run --rm -c "poetry run pytest tests/test_cbc.py"
