name: CI tests incl. CBC solver

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

defaults:
  run:
    shell: bash

jobs:
  tests:
    name: Build and test oogeso
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Dockerfile
        run: docker pull haraldsvendsen/oogeso
      - name: Test Oogeso
        run: docker run --rm -w /code -v "$(pwd):/code" haraldsvendsen/oogeso bash -c "poetry install && poetry run pytest"
      - name: Test Example Notebooks
        run: docker run --rm -w /code -v "$(pwd):/code" haraldsvendsen/oogeso bash -c "poetry install --all-extras && poetry run pytest --nbmake ./examples"
