name: CI tests

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

defaults:
  run:
    shell: bash

jobs:
  tests:
    name: Build and test oogeso
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Dockerfile
        run: docker build --pull -t oogeso --target test -f Dockerfile .
      - name: Test cbc
        run: docker run --rm oogeso bash -c "poetry run pytest"
      - name: Test notebooks
        run: docker run --rm oogeso bash -c "poetry run  pytest --nbmake ./examples -k 'test_'"  # Run only test_*

