name: Docker Hub Publish

# Daily build from master at 00:00. Can also be triggered manually from master if needed.
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
    - 'Dockerfile'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU  # Needed for multi-platform image
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx  # Needed for multi-platform image
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/oogeso:latest
