name: Docs CI/CD
on:
  push:
    branches:
    - master  # Note: We build this based on changes in master. Could be changed to build at release/publish later.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v4.3.0

    - uses: actions/checkout@master
      with:
        fetch-depth: 0

    - name: Setup Python 3.11
      uses: actions/setup-python@v4.3.0
      with:
        python-version: '3.11'

    - uses: snok/install-poetry@v1.3.3
      with:
        virtualenvs-create: true

    - name: Build documentation
      run: |
        mkdir gh-pages
        touch gh-pages/.nojekyll
        cd docs/
        poetry check --no-interaction
        poetry install --no-interaction
        poetry run make html
        cp -r _build/html/* ../gh-pages/

    - name: Deploy documentation
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: gh-pages
